# Generated by Django 5.0.3 on 2024-03-31 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaveBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=50, unique=True)),
                ('owner_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField()),
                ('message_id', models.PositiveIntegerField()),
                ('slavebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slavebot')),
            ],
        ),
    ]
